version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@knapsack/*"
    groups:
      knapsack-packages:
        patterns:
          - "@knapsack/*"
    commit-message:
      prefix: "deps"
