version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@knapsack/*"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 1
    labels:
      - "knapsack-dependencies"
    versioning-strategy: increase
    target-branch: "main"
