version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "knapsack/*"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
