# Helpful Doc Links
# Workflow syntax - https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Context and expression syntax - https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: Handle Deploy

on: deployment_status

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    env:
      REPO_SLUG: knapsack-cloud/Instance-1
    steps:
      - name: Placeholder
        run: |
          echo "Heard about a deployment!"
