name: Label Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Add 'dependencies' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'dependencies'
