name: Label Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Add 'knapsack-dependencies' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'knapsack-dependencies'
